# This file defines which GitHub labels get applied when files
# matching certain minimatch glob patterns are changed.
#
# Documentation: https://github.com/actions/labeler#pull-request-labeler
#
# If a label includes a space or a pattern begins with an asterisk or
# special character, enclose it in quotes.

Breaking:
- changelog/*.breaking*.rst

Bug:
- changelog/*.bugfix*.rst

'Continuous Integration':
- .codecov.yaml
- .github/workflows/*test*.yml
- .pre-commit-config.yaml
- CODEOWNERS
- noxfile.py
- tox.ini

'Contributor Guide':
- changelog/README.rst
- docs/contributing/**/*

dependencies:
- requirements.txt

Documentation:
- docs/**/*
- changelog/*doc*.rst
- README.md
- .readthedocs.yml

'GitHub Actions':
- .github/**/*

Notebooks:
- docs/notebooks/**/*

Packaging:
- .github/workflows/*publish*
- .github/workflows/*release*
- MANIFEST.in
- pyproject.toml
- setup.*

plasmapy.analysis:
- plasmapy/analysis/**/*

plasmapy.diagnostics:
- plasmapy/diagnostics/**/*

plasmapy.dispersion:
- plasmapy/dispersion/**/*

plasmapy.formulary:
- plasmapy/formulary/**/*

plasmapy.formulary.quantum:
- plasmapy/**/quantum*

plasmapy.particles:
- plasmapy/particles/**/*

plasmapy.plasma:
- plasmapy/plasma/**/*

plasmapy.simulation:
- plasmapy/simulation/**/*

plasmapy.utils:
- plasmapy/utils/**/*

Testing:
- '**/test*.py'
- '**/conftest.py'
- .github/workflows/weekly.yml
- .codecov.yaml
- noxfile.py
- tox.ini
